/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CategoryForm: typeof import('./src/components/category/CategoryForm.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    OrganizationForm: typeof import('./src/components/organization/OrganizationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceLineForm: typeof import('./src/components/service_line/ServiceLineForm.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    VesselForm: typeof import('./src/components/vessel/VesselForm.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
